# Generated by Django 4.2.6 on 2023-10-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('symbol', models.CharField(max_length=10)),
                ('capital', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('continent', models.CharField(max_length=100)),
                ('continentCode', models.CharField(max_length=2)),
                ('alpha3', models.CharField(max_length=3)),
            ],
        ),
    ]
