# Generated by Django 4.2.6 on 2023-10-05 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inderr.countries')),
            ],
        ),
    ]
