# Generated by Django 4.2.6 on 2023-10-05 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0002_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inderr.states')),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5)),
                ('district_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inderr.district')),
                ('divisions_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inderr.divisions')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='division_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inderr.divisions'),
        ),
    ]
