# Generated by Django 4.2.6 on 2023-10-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0003_district_divisions_stations_district_division_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station_f', to='inderr.stations')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station_f', to='inderr.stations')),
            ],
        ),
    ]
