# Generated by Django 4.2.6 on 2023-10-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0004_trains'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stations',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='TrainInnerStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inderr.stations')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inderr.trains')),
            ],
        ),
    ]
