# Generated by Django 4.2.6 on 2023-10-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0005_stations_lat_stations_lon_traininnerstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='trains',
            name='friday',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='monday',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='saturday',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='sunday',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='thursday',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='tuesday',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='trains',
            name='wednesday',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
