# Generated by Django 4.2.6 on 2023-10-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0006_trains_friday_trains_monday_trains_saturday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininnerstation',
            name='arrives',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='traininnerstation',
            name='avg_delay',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='traininnerstation',
            name='day',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='traininnerstation',
            name='departs',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='traininnerstation',
            name='distance',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='traininnerstation',
            name='halt_time',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
