# Generated by Django 4.2.6 on 2023-10-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0008_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininnerstation',
            name='is_stop',
            field=models.BooleanField(default=False),
        ),
    ]
