# Generated by Django 4.2.6 on 2023-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0009_traininnerstation_is_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lat', models.DecimalField(decimal_places=8, default=None, max_digits=9, null=True)),
                ('lon', models.DecimalField(decimal_places=8, default=None, max_digits=9, null=True)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
