# Generated by Django 4.2.6 on 2023-10-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0010_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='temp',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9, null=True),
        ),
    ]
