# Generated by Django 5.0.2 on 2024-04-01 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0011_alter_temp_lat_alter_temp_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coarch_no', models.CharField(max_length=5)),
                ('train_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inderr.trains')),
            ],
        ),
    ]
