# Generated by Django 5.0.2 on 2024-04-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0012_configinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configinfo',
            old_name='coarch_no',
            new_name='coach_no',
        ),
        migrations.RenameField(
            model_name='configinfo',
            old_name='train_no',
            new_name='train',
        ),
    ]
