# Generated by Django 5.0.2 on 2024-05-28 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0014_trackingdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configinfo',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
