# Generated by Django 5.0.2 on 2024-06-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0017_trackingdata_config_trackingdata_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='has_translator',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='states',
            name='language_code',
            field=models.CharField(default='hindi', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='states',
            name='official_language',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
