# Generated by Django 5.0.2 on 2024-08-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0018_states_has_translator_states_language_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestartLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.BigIntegerField()),
                ('tracking_log_id', models.BigIntegerField()),
            ],
        ),
    ]
