# Generated by Django 5.0.2 on 2024-08-23 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inderr', '0019_restartlogs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('curr_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('curr_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('remaining_distance', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('is_crossed', models.BooleanField(default=False)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('abbr', models.CharField(blank=True, max_length=10, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('total_distance', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('estimate_time', models.TimeField(blank=True, null=True)),
                ('depart_time', models.TimeField(blank=True, null=True)),
                ('halt_time', models.IntegerField(blank=True, null=True)),
                ('total_time_to_reach', models.DateTimeField(blank=True, null=True)),
                ('instant_distance', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('instant_speed', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('late_by', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inderr.configinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
